modules:
  LegacyCombatModule:
    enabled: true
    disableEntityCramming: true
    disableEnderpearlCooldown: true
    disableSwingSounds: true
    disableSweep: true
    legacyCrits: true
    legacyAttackSpeed: true
    armorDurability: true
    projectileDamage: true
    armorDurabilityReduction: 1
    noDamageTicks: 19
    attackSpeed: 16
    projectileRandomnessValue: 0.1
    regenInterval: 3990
    regenHealAmount: 1
    regenExhaustionHealAmount: 3
  StaffModModule:
    enabled: true
    xray: "apollo.staffmods.xray"
  WaypointModule:
    enabled: true
    waypoints:
      - Spawn: # The same name as the waypoint.
          x: 0 # Must be a number, -inf->inf. No decimals. No quotes.
          y: 100 # Must be a number, 0->255. No decimals. No quotes.
          z: 0 # Must be a number, -inf->inf. No decimals. No quotes.
          name: "Spawn" # MUST be a word, and MUST be in quotes.
          world: "world" # MUST be a word, and MUST be in quotes. MUST be a valid world name.
          color: 0xFF0000 # MUST be a hexadecimal representation of a number.
          forced: false # MUST be either a true or false value. No quotes.
          visible: true # MUST be either a true or false value. No quotes.
  ModSettingsModule:
    # Mod Ids: (Last Updated: 05/05/2021)
    # one_seven_visuals - 1.7 Visuals
    # fps - FPS
    # cps - CPS
    # skyblockAddons - Skyblock Addons
    # toggleSneak - Toggle Sneak/Sprint
    # hypixel_mod - Hypixel Mods
    # armorstatus - Armor Status
    # keystrokes - Key Strokes
    # coords - Coordinates
    # crosshair - Crosshair
    # potioneffects - Potion Effects
    # directionhud - Direction HUD
    # waypoints - Waypoints
    # scoreboard - Scoreboard
    # potion_counter - Potion Counter
    # ping - Ping
    # motionBlur - Motion Blur
    # chat - Chat
    # scrollable_tooltips - Scrollable Tooltips
    # uhc_overlay - UHC Overlay
    # particleMultiplierMod - Particle Multiplier
    # cooldowns - Cooldowns
    # worldedit_cui - WorldEdit CUI
    # clock - Clock
    # stopwatch - Stopwatch
    # memory - Memory Usage
    # combo - Combo Counter
    # range - Reach Display
    # time_changer - Time Changer
    # serverAddressMod - Server Address
    # saturation - Saturation
    # itemPhysic - Item Physics
    # itemTrackerChild - Item Tracker
    # shinyPots - Shiny Pots
    # block_outline - Block Outline
    # screenshot - Screenshot Uploader
    # fov_mod - FOV Mod
    # textHotKey - Auto Text Hot Key
    # netgraph - Net Graph
    # mumble-link - Mumble Link
    # bossbar - Boss Bar
    # freelook - Freelook
    # replaymod - ReplayMod
    # nickHider - NickHider
    enabled: true
    settings:
      - "skyblockAddons"
  EVNTModule:
    enabled: true
  ServerRuleModule:
    enabled: true
    competitiveGame: false
    shadersDisabled: false
    disableF6Broadcasting: false # Only needed/available on 1.7 & 1.8
    antiPortalTraps: false # work in progress
    cpsLimiter: false # Work in progress
    cpsLimit: 20 # Work in progress

