metadata.format.version = "1.1"

[versions]
adventure = "4.24.0"
adventurePlatform = "4.4.1"
artifactregistry = "2.2.1"
bukkit = "1.8.8-R0.1-SNAPSHOT"
bungee = "1.21-R0.4"
configurate = "4.2.0+lunar.5"
geantyref = "1.3.11"
idea = "1.1.7"
jetbrains = "24.0.1"
lombok = "1.18.38"
protobuf = "0.0.2"
gson = "2.10.1"
shadow = "8.1.1"
spotless = "6.13.0"
velocity = "3.3.0-SNAPSHOT"
folia = "1.20.1-R0.1-SNAPSHOT"
asm = "9.7.1"
minestom = "2025.08.18-1.21.8"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# adventure
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventurePlatform" }
adventure-platform-bungee = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventurePlatform" }
adventure-textserializergson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventure-textserializergson-legacy = { module = "net.kyori:adventure-text-serializer-gson-legacy-impl", version.ref = "adventure" }
adventure-textserializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }

# api
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }

# common
protobuf = { module = "com.lunarclient:apollo-protos", version.ref = "protobuf" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }

# bukkit
bukkit-api = { module = "org.spigotmc:spigot-api", version.ref = "bukkit" }
bukkit = { module = "org.spigotmc:spigot", version.ref = "bukkit" }

# folia
folia = { module = "dev.folia:folia-api", version.ref = "folia" }

# bungee
bungee = { module = "net.md-5:bungeecord-api", version.ref = "bungee" }

# velocity
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }

# minestom
minestom = { module = "net.minestom:minestom", version.ref = "minestom" }

# build
artifactregistry = { module = "gradle.plugin.com.google.cloud.artifactregistry:artifactregistry-gradle-plugin", version.ref = "artifactregistry" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
shadow = { module = "com.github.johnrengelman:shadow", version.ref = "shadow" }
idea = { module = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext", version.ref = "idea" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }

stylecheck = "ca.stellardrift:stylecheck:0.1"

[bundles]

adventure = ["adventure-api", "adventure-textserializergson", "adventure-textserializergson-legacy", "adventure-textserializer-legacy"]
