metadata.format.version = "1.1"

[versions]
artifactregistry = "2.2.0"
bukkit = "1.8.8-R0.1-SNAPSHOT"
bungee = "1.19-R0.1-SNAPSHOT"
configurate = "4.2.0-SNAPSHOT"
geantyref = "1.3.11"
idea = "1.1.7"
jetbrains = "24.0.1"
lombok = "1.18.26"
protobuf = "1.0-SNAPSHOT"
gson = "2.10.1"
shadow = "7.1.2"
spotless = "6.13.0"
velocity = "3.0.1"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# api
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }

# common
protobuf = { module = "com.lunarclient:apollo-protos", version.ref = "protobuf" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }

# bukkit
bukkit-api = { module = "org.spigotmc:spigot-api", version.ref = "bukkit" }
bukkit = { module = "org.spigotmc:spigot", version.ref = "bukkit" }

# bungee
bungee = { module = "net.md-5:bungeecord-api", version.ref = "bungee" }

# velocity
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }

# build
artifactregistry = { module = "gradle.plugin.com.google.cloud.artifactregistry:artifactregistry-gradle-plugin", version.ref = "artifactregistry" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
shadow = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "shadow" }
idea = { module = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext", version.ref = "idea" }

stylecheck = "ca.stellardrift:stylecheck:0.1"
