blank_issues_enabled: false
contact_links:
    - name: â“ Questions & Feature Request
      url: https://lunarclient.com/developers-discord
      about: Join our Discord to ask questions and request features for Apollo.
    - name: ğŸ“„ Documentation
      url: https://lunarclient.dev/apollo/introduction
      about: Visit our documentation page to understand Apollo better.
