blank_issues_enabled: false
contact_links:
    - name: â“ Questions & Feature Request
      url: https://discord.gg/3T9Atyb6pf
      about: Join our Discord to ask question and request features for Apollo.
    - name: ğŸ“„ Documentation
      url: https://lunarclient.dev/apollo/introduction
      about: Visit our documentation page to understand Apollo better.
